In [3]:
import gym
import numpy as np
import matplotlib.pyplot as plt
import gym
import jax
import coax
import haiku as hk
import jax.numpy as jnp
from numpy import prod
import optax

ModuleNotFoundError: jax requires jaxlib to be installed. See https://github.com/google/jax#installation for installation instructions.

In [1]:

from envus import smiba_build

In [1]:
import gym
import smiba_dae


In [2]:
gym.envs.register(
     id='SmibaDAE-v2',
     entry_point='envus.smiba:SmibaDAE',
     max_episode_steps=100
)
env = gym.make('SmibaDAE-v2')

In [7]:
env.reset()


array([ 0.9978529 ,  1.0078309 ,  0.49921614, -0.10462663], dtype=float32)

In [20]:
env.step(2)

(array([ 0.9899659 ,  1.0024322 ,  0.06140837, -0.505955  ], dtype=float32),
 -0.005915897094645818,
 False,
 {})

In [6]:
env.dae.report_u()

p_m   = 0.50
v_f   = 2.00


In [19]:
env.dae.xy

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])