In [1]:
import numpy as np
import numba
import pendulum
import gym


In [2]:
env = gym.make('PendulumDAE-v0')

In [3]:
env.reset()

array([-0.81145966, -0.5844084 , -0.8584258 ], dtype=float32)

In [8]:
env.step(np.array([0.0]).astype(np.float32))

(array([-0.8871219 , -0.46153516, -1.7339915 ], dtype=float32),
 -6.411202845216917,
 False,
 {})

In [9]:
env.step(np.array([0.0]).astype(np.float32))

(array([-0.9268386 , -0.37546006, -2.0489488 ], dtype=float32),
 -7.38621252171419,
 False,
 {})

In [46]:
env.reset()
times = np.arange(0,10,0.1)

for t in times:
    step(model,t,{'u':0.01})
    #print(model.xy)
    
model.ini({'u':0.0})
times = np.arange(0,10,0.1)

for t in times:
    step(model,t,{'u':0.01})
    #print(model.xy)

In [47]:
model.report_u()

u     = 0.01
u_dummy = 1.00


In [13]:
%%timeit

env.reset()
times = np.arange(0,10,0.1)

for t in times:
    env.step(np.array([0.0]).astype(np.float32))
    #print(model.xy)

20.7 ms ± 7.31 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [42]:
model.Dt = 0.1